Ros release 2.26 (#1030)
* Throw error when indexing non-existing message, changed example to use disparity

* Improved example

* Clangformat

* Bump fw

* Bump fw

* Bump shared

* Changed syncThreshold setter to use chrono duration

* Bump shared

* Bump fw

* Handle shutdown returning false, bump fw

* Bump fw

* Changed the way crash reports are retrieved

* Bump fw

* Clangformat

* Bump fw

* Bump fw

* IR Intensity API (#924)

* Ir brightness control based on normalized intensity, instead of current.

* Added IR intensity API

* Update docstring. Point to correct device side commit.

* Deprecated ir brightness api, fixed spatial_calculator_multi_roi example.

* Update depthai-shared, update FW.

* Sync shared with device side

* Update shared on device and host

* Bump FW to latest develop

* Bump FW - bumped shared to latest.

* Rename connectivity enum

* Update README

* Minor encframe test fixes

* Bump fw

* Added DEPTHAI_CRASHDUMP_TIMEOUT to determine crashdump timeout

* TODO fix windows test

* Changed crashdump timing

* Bump shared

* Clangformat

* Fix readme

* Bump fw

* Bump shared

* Bump fw and XLink

* Bump fw

* Add an example with IMU

* Add new line at the end of the example

* [RVC2 FW] Update FW with updated shared

* added docstring for fisheye

* Check for crash dump before getting

* Update FW with a stability fix for timesync

* Revert the XLink profiling to uint64_t change

* Update FW and shared to develop

* Fix the xlink profiling

* Bump version to 2.24.0

* Fix build with gcc 13.2 toolchain

To fix a couple compile errors along these lines,

/usr/include/fmt/core.h: In instantiation of 'constexpr fmt::v10::detail::value<Context> fmt::v10::detail::make_arg(T&)
-- snip some typical C++ compiler noise --
src/device/DataQueue.cpp:296:45:   required from here
/usr/include/fmt/core.h:1580:7: error: static assertion failed: Cannot format an argument.

avoid trying to format atomic_t directly, and instead pass in the simple type being
protected by that atomic_t (which in this case, is size_t).

Signed-off-by: S. Lockwood-Childs <sjl@vctlabs.com>

* Bump fw

* Implemented PointCloudData message

* Added PCL support

* PCL Bugfixes

* Added combined target

* Fixed large buffer processing in MessageGroups

* Improved pcl example

* Fix test

* clangformat

* Fix a bug where watchdog is created and destroyed more than once

* Added rgb pointcloud capability

* Revert "Added rgb pointcloud capability"

This reverts commit 56e3c0b2e76716e1e47a4dc6c4bbe0f2623cf125.

* Bump shared

* Revert shared

* Bump fw

* Implemented sparse pointclouds

* Clangformat

* Bump fw

* [RVC2] getStereoPairs (#941)

* getStereoPairs. Skip getAvailableStereoPairs for now, since it may give weird results on RAE, or similar setups...

* Formatting

* Added isVertical to serialize

* Updated device side shared

* Impl << operator for StereoPair and vector<StereoPair>

* getAvailableStereoPairs

* Address https://github.com/luxonis/depthai-core/pull/941#discussion_r1460988267

* Bump device side to develop.

* Point shared to develop

* [FW] point to same depthai-shared (ci fix)

* Fix windows build.

* Make the getSystemInformationLoggingRate() function work

* Fix std::initializer_list reassignment

* Added some pointcloud tests

* Add intensity output

* Remove deprecated methods, change toPclData to getPclData

* Added ability to set the lens position via a float, to enable a more precies movement. (#954)

* Added lensPositionRaw to ImgFrame and EncodedFrame

* Updated videoEnc comments so docs will be updated.

* Add missing includes. Fixes #964

* Add fw commit

* Update depthai-shared

* FW: fix CAM_C failing to stream in certain cases,
with same sensor type on CAM_B

* Support for OAK-T (#950)

* thermal node for testing

* Host thermal, for testing

* added nnet experiment, non working... thermal2 experimenting

* Cleanup Thermal node remains, clean up the example.

* [FW] Add support for thermal.

* Sync shared with device side, remove thermal nnet example for now, will add later when it works. Update device side commit.

* Fix  fw build.

* Update examples/Camera/thermal_cam.cpp

Co-authored-by: TheMarpe <martin@luxonis.com>

* [FW] detect oak-ts with the new board name

* shared

* [FW] Drive IR leds in torch mode on oak_t. To get max brightness out of the leds both need to be enabled, using: setIrLaserDotProjector... setIrFloodLight... apis

* Fix signal integrity issues at high ambient temperatures.

* Bump shared

* Added some comments to thermal_cam example.

* Merged device side.

* Remove thermal_cam example from tests

---------

Co-authored-by: TheMarpe <martin@luxonis.com>

* Add writeCcmEepromRaw RPC

* DataQueue: catch packet parsing errors and return a null packet instead, with an `error` log

* StreamMessageParser: add more details (size etc) to the 'bad packet' exceptions thrown

* Example fixes & improvements, bump fw

* Clangformat

* Bugfix

* ToF: add phase map output

* Changed outdated code

* Reduce amount of pointcloud copying

* Pointcloud test fix

* Tests fix 2

* Fix sparse pointcloud min z, fix tests

* Add missing test argument

* Alway join threads

* Update README.md

* Added transformation matrix support to pointcloud

* Rename functions, update shared

* Update depth align node, fix crash

* Enhance camera features (#973)

* Improve reporting of camera features. Added calibrationResolution and added fov rect to CameraSensorConfig

* FW: -fix `setAutoExposureLimit` flicker during AF lens move,
- IMX214 4K resolution timings were slightly off, also bump max FPS for it (up to 34),
- VideoEncoder fix artifacts for multiple monochrome streams with different resolutions (OV9282 and AR0234),
- fix potential crash with Script GPIO.setInterrupt with too high priority (<= 15, low value = high prio)

* Bump version to 2.25.0

* Fix compiler warning

* Move optimization for config

* Update pointcloud data comments

* Update comments for the PointCloud node

* Expose the pool size for the pointcloud

* Change to RH system

* Update FW to develop

* TMP FW with more logging for bad-packet debugging. Fix ImageManip potential OsDrvCpr crash

* FIx macos build

* Clean up comments

* Remove irrelevant change

* Add decoding pipeline

* Try to fix a FW memory alignment issue

* fix finding jsoncpp

* FW: fix fsync for OAK-D-SR

* Change IMU fw update status to int

* Add cast node

* Fix typo in docstring

* Update Cast node with fixes

* Handle multi input NN

* Update ToF decoding algorithm

* Update FW; fixed optical correction

* Optimize wiggle correction

* Handle edge cases; unsupported distortion coefficients

* Add tilt projection support

* Add phase unwrapping

* Update phase unwrapping, add configurable levels

* Device: add RPC setXLinkRateLimit for device transmit bandwidth throttling

* Introduced `DeviceBootloader::getFlashedVersion` to retrieve the bootloader version flashed on the device. Fixed `isUserBootloaderSupported` - thereby fixed user bootloader flashing. (#997)

* Introduced DeviceBootloader::getFlashedVersion to retrieve the bootloader version flashed on the device. Fixed isUserBootloaderSupported - thereby fixed user bootloader flashing.

* Applied the suggestions

* Fix sensor configs for ov9282/ov9782 (differentiate between color/mono when possible)

* FW: fixes for IMX378 and IMX582:
fix concurrent run,
fix scaling with IMX378 THE_1352X1012 resolution,
change Camera node best sensor config select to prioritize matching aspect ratio

* Optimized decoding pipeline: 60->27 ms

* Add jsoncpp with hunter

* Make PCL include optional

* Fixed booting issue on OAK D SR POE and OAK T. (#1002)

* Fail loudly if PCL enabled, README changes

* Conditionally add jsoncpp package

* Add multi shave support for ToF decoding

* Update ToF decoding: handle arbitrary sensor rotation

* FW: fix default fsync GPIO state for OAK-FFC-4P R7,
FSIN_4LANE GPIO42 = input, pull-down

* Add phaseUnwrappingErrorThreshold config

* Release 2.25.1 (#1005)

* fix finding jsoncpp

* FW: fix fsync for OAK-D-SR

* Change IMU fw update status to int

* Add tilt projection support

* Introduced `DeviceBootloader::getFlashedVersion` to retrieve the bootloader version flashed on the device. Fixed `isUserBootloaderSupported` - thereby fixed user bootloader flashing. (#997)

* Introduced DeviceBootloader::getFlashedVersion to retrieve the bootloader version flashed on the device. Fixed isUserBootloaderSupported - thereby fixed user bootloader flashing.

* Applied the suggestions

* Fix sensor configs for ov9282/ov9782 (differentiate between color/mono when possible)

* FW: fixes for IMX378 and IMX582:
fix concurrent run,
fix scaling with IMX378 THE_1352X1012 resolution,
change Camera node best sensor config select to prioritize matching aspect ratio

* Add jsoncpp with hunter

* Make PCL include optional

* Fixed booting issue on OAK D SR POE and OAK T. (#1002)

* Fail loudly if PCL enabled, README changes

* Conditionally add jsoncpp package

* FW: fix default fsync GPIO state for OAK-FFC-4P R7,
FSIN_4LANE GPIO42 = input, pull-down

* Bumped version to 2.25.1

* Fix FFC3P - not found after booting if ov9282 is connected.

* Make getAllConnectedDevices consistent when no devices are found

---------

Co-authored-by: Serafadam <serafadam@gmail.com>
Co-authored-by: alex-luxonis <alex@luxonis.com>
Co-authored-by: asahtik <asahtik@gmail.com>
Co-authored-by: SzabolcsGergely <szabi@luxonis.com>
Co-authored-by: asahtik <38485424+asahtik@users.noreply.github.com>
Co-authored-by: Matevz Morato <matevz.morato@gmail.com>
Co-authored-by: moratom <47612463+moratom@users.noreply.github.com>

* FW: fix S5K33D ToF streaming when enabled on both sockets B and C,
shared I2C bus

* Fix feature tracker ID type deduction

* FW: fsync shift on custom board

* Add new eeprom content

* Update FW: DepthAlign node implementeD

* Update TOF decoding/eeprom content

* Added enableBurstMode=false and enablePhaseShuffleTemporalFilter=true options.

* Fall back to sensor EEPROM if onboard intrinsics or distortion coefficients are not found

* Update temperature coefficients

* FW, BL: fix a potential bootup/reboot failure,
that required power cycle to recover from

* Update FW; 10 bit amplitude, uint16; temperature calibration version check

* Update interface

* Fix stride size

* (fix mistake in previous commit, FW ver was put in the wrong place)

* Revert "DataQueue: catch packet parsing errors and return a null packet instead, with an `error` log". Note:
reason for revert was underlying cause likely fixed, we'll probably revisit in future and keep exception throwing but not closing the queues on these potential bad packets

This reverts commit 1a48df97e1a1bae9ef7eee798d3ebbaf99d01085.

* Refactor DepthAlign -> ImageAlign

* Remove readCcmEepromRaw, writeCcmEepromRaw

* BL: update to 0.0.28 release version (bootup/restart fixes)

* StreamMessageParser: check end-of-packet bytes, warn on mismatch,
the warning usually can be ignored, but may indicate some issues

* FW: update after merge. Fix style - `make clangformat`

* Fix CI

Remove CMake 3.10 test on macos-latest

* DeviceBootloader: warning for potentially unstable flashed bootloader < 0.0.28

* FW: fix for MessageGroup parsing after the added end-of-packet marker

* StreamMessageParser: apply end-of-packet marker in both directions

* FW: stream parser marker merged, other changes: warp FP16

* Update FW

* FW: ToF double raw stream FPS internally to get depth at configured FPS,
for the default case (non-burst mode). Other ToF changes:
- fix timestamps and sequence numbers
- reduce device CPU load when ToF streams, depending on FPS
- set the proper ToF exposure time in ImgFrame metadata, 796us max
- warnings for FPS capping, 80 max recommended, 88 max possible (with reduced depth quality far away)

* Update FW; handle edge cases

* bump changelog

* remove pcl dependency

* ImageAlign: add multi shave support

* [FW] Update FW with better increased MIPI priority for cameras

* clangformat

* Remove tau character from comments

* Add the align examples

* Remove unused example

* Add the cast examples

* Add the tof depth example

* Add spatial examples for yolo

* [FW] Update FW to develop

* Cleanup

* Clangformat

* Bump version to v2.26.0

* FW: fix timings for OV9282 fsync at 400p on CAM_A

* bump changelog and version

---------

Signed-off-by: S. Lockwood-Childs <sjl@vctlabs.com>
Co-authored-by: asahtik <asahtik@gmail.com>
Co-authored-by: asahtik <38485424+asahtik@users.noreply.github.com>
Co-authored-by: Filip Jeretina <59307111+zrezke@users.noreply.github.com>
Co-authored-by: alex-luxonis <alex@luxonis.com>
Co-authored-by: alex-luxonis <60824841+alex-luxonis@users.noreply.github.com>
Co-authored-by: moratom <47612463+moratom@users.noreply.github.com>
Co-authored-by: Matevz Morato <matevz.morato@gmail.com>
Co-authored-by: saching13 <sachin.guruswamy@gmail.com>
Co-authored-by: Martin Peterlin <martin.peterlin7@gmail.com>
Co-authored-by: S. Lockwood-Childs <sjl@vctlabs.com>
Co-authored-by: TheMarpe <martin@luxonis.com>
Co-authored-by: Jakob Socan <10517617+jakgra@users.noreply.github.com>
Co-authored-by: Tommy <tomprochazka0@gmail.com>
Co-authored-by: Erol444 <erol123444@gmail.com>
Co-authored-by: Tommy Walker <77851258+whoactuallycares@users.noreply.github.com>
Co-authored-by: SzabolcsGergely <szabi@luxonis.com>
Co-authored-by: jakaskerl <53253318+jakaskerl@users.noreply.github.com>
Co-authored-by: Szabolcs Gergely <60790666+SzabolcsGergely@users.noreply.github.com>