Ros release 2.21.0 (#795)
* Several FW updates:
- !!! For all sockets/cameras to be scanned, the EEPROM calib data boardName/productName should contain "FFC" or an FFC-related board name: 1090/2090/2088. Otherwise the behavior is to scan only for standard OAK devices sockets/cameras
- Some more checks for the LCM48 (on MAX) supported resolutions
- Fixes for RGB-mono SW-sync for standard OAK-D / OAK-D-Lite camera configs
- AR0234 monochrome support, however needs an OV9282 enabled at the same time for now

* Color/MonoCamera: handle some more cases for newly added resolutions/sockets

* Update shared/FW after merge, fix error log printed for MonoCamera AUTO socket

* Closes: #355

* Bump version to 2.18.0

* Updated FW with some Color/MonoCamera fixes

* stability test

* Update FW:
- fix for high system load crash, especially on PoE devices
- for for OV9282 as MonoCamera on RGB/CAM_A socket

* FW: OV9282 720p/800p max FPS: 60 -> 120

* stability test

* Added a convinience setTimesync function

* Added isUserBootloaderSupported to DeviceBootloader

* Updated XLink with Windows improvements when scanning for already booted USB devices

* Updated FW with device time reset on boot

* Bump to v2.19.0

* Improved wording on unavailable devices

* Fix yolo v5 decoding when there is a single class

* FW: fixes for certain OV9782 and OV9282 permutations/configs,
fix for OV9782/OV9282 alone failing on RGB/CAM_A socket

* Update CI to Node16 compatible actions

* Update FW: fix image size when decimation filter is enabled

* Stability test - limit FPS (#633)

* Print CPU usage

* Limit the FPS so POE devices aren't maxed out

* Increase FPS

* Reverse changes to the system logger example

Co-authored-by: TheMarpe <martin.peterlin7@gmail.com>
Co-authored-by: Matevz Morato <matevz.morato@gmail.com>

* Added getProductName

* Added ids to IO for trace events

* Modified pipeline schema dump to happen on trace log level as well

* Renamed to getDeviceName and added some legacy handling

* Updated FW with productName as protected field and ImageManip behavior revert

* Updated style

* Added IR driver support for new OAK-FFC 4P

* FW: bugfix for device bootup with default static IP

* OAK-FFC 4P R5M1E5 IR/Dot support

* Bump to v2.19.1

* Added EepromError exception class and improved exception handling in calibration related methods

* Increased limit on DeviceBootloader monitor timeout

* Fixed check for user-provided toolchain file when given relative path (#645)

* Fixed check for user-provided toolchain file when given relative path

* WIP: camera/socket board configuration and capability to specify name/alias for a camera instead of socket

* Updated Bootloader to v0.0.22

* Added camera naming capabilites, setting and retrieving. WIP: rest of devices

* FW/CameraControl: fix still-capture for sockets other than RGB/center

* [FW] Fixed ImageManip + Subpixel issues and added FFC camera naming

* get/set camera FrameEvent filter

* Update depthai-shared submodule

* Disable depthai-shared commit hash check

* Change github workflows ubuntu version

* Update submodule

* Rename event filter

* fix luxonis/depthai-core#650 missing XLinkProtocolToStr() (#657)

- add local xlinkproto -> string from
  luxonis/XLink/tree/5c61615066af6539e50a4a17b5df3466e4350b21

* Updated grammar

* Update firmware

* WIP: Camera node

* Added capability to set XLink logging level via XLINK_LEVEL env var

* Replace "_CMAKE_" variables with "_DEPTHAI_" (#662)

"_CMAKE_" variables are reserved for internal use and should not be used.
This change also makes it harder for other CMake scripts to accidentall overwrite this variable.

Co-authored-by: Cameron Blomquist <cblomquist@lsa2.com>

* Add comments

* Update FW: Add missing python bindings for boundingBoxMapping

* Updated NETWORK Bootloader with dual protocol capabilities

* [FW] Fixed a bug in board downselection. OAK-D S2/Pro camera enumeration fix.

* [FW] Added support for Mono video/preview in Camera node

* CI - Fixed style & tidy jobs

* Updated dual BL to v0.0.23 temporary build

* Added OAK-D-LR support. WIP: Orientation capability

* [FW/XLink] Explicitly limited to single connection

* ImageManip added colormap capability. TODO min/max range selection

* Add option to override baseline and/or focal length for disparity to depth conversion

* [FW] OAK-D-LR - Fixed default image orientation

* Updated brief description that affects docs of the DetectionParser node.

* Modified API of Camera a bit

* Updated FW with Camera changes and warp capabilities

* Updated FW with Camera warp capabilities

* Added dai::span

* Added undistort/warp API to Camera node

* FW - Modifed watchdog to do a graceful reset instead

* Added additional API to retrieve timestamps at various exposure points

* Fixed documentation on ObjectTracker::setMaxObjectsToTrack

* WIP: mockIsp capabilities

* [FW] Fix for CAM_C not being detected

* Device - Added non exclusive boot option

* Slight Colormap API improvements

* [FW] Added OpenVINO version 'universal'

* Added DeviceBase convinience constructors taking name or deviceid as string

* Add mode and median support to SLC

* Disabled some of the functionality for now

* Tweaked getTimestamp & exposure offset API

* FW: IMX296 support, added THE_1440x1080 resolution

* FW: IMX296 Camera node, IMX378 1080p limited to 60fps

* Bump version to 2.20.0

* Applied formatting

* Temporary revert to macos-11 for CI due to Catch2 issues

* Update FW, API

* Update FW

* Modified OpenVINO::VERSION_UNIVERSAL

* Updated Bootloader to 0.0.24

* Bump version and FW to 2.20.1 (Status LEDs improvement)

* calibration_flash example fix

* Fixed api docs for Warp HW ids

* FW: fix crash with ColorCamera at high resolution and certain ISP scaling

* FW: fix crash with ColorCamera at high resolution and certain ISP scaling

* Bump version to 2.20.2

* Added an ColorCamera isp scale example, and modified test workflow

* Implement multi stereo support

* Implement brightness filter

* FW: fix OV9282 SW-sync on devices with OV9782 RGB camera

* Update FW: Fix OOM due to too many SIPP pipelines

* Modified default device config OpenVINO version to universal

* Merge branch 'catch2_update'

* FW: handle EEPROM `boardOptions` bit 7 for separate I2C on L/R

* FW: fix for IMX378/477/577 on sockets other than RGB

* Update FW: support for stereo alignment to original left or right inputs; OOM fix for 4 stereo nodes with median filter

* Update FW: parsing optimization and improvements for Yolo v6, v6r2, v8

* Update FW w/ syncing stall fix

* Update stereo with more robust frame sync

* Update FW with optional override of spec translation for stereo algorithm calculations

* Correct type

* Update SPIOut.hpp

to address error C4458: declaration of 'id' hides class member

* Expose center alignment scale factor for debug purposes

* Expose SIPP mempool configurable sizes

* Update FW

* Fixed usage of DeviceBootloader with incomplete DeviceInfo and added a convinience constructor

* Closes: #714

* Add alpha scaling option for StereoDepth

* Update FW before merge

* Update FW with RGB alignment fix

* Update FW with performance metrics when DEPTHAI_LEVEL=info is enabled; enable brightness filter for 0 intensity pixels by default

* Improve spatial calculation X and Y accuracy; fix RGB alignment when custom output depth size is specified

* [XLink] Increased max number of links from 32 to 64

* Add crash dump functionality

* Change API to return just crash dump

* Update FW with commit hash attached to crash dump

* Update FW with fix for serialization of thread name

* Add hasCrashDump API

* Update FW

* Update FW, crash dump contains device ID

* Enable MEDAIN spatial calculation method for SpatialDetectionNetwork

* Update FW

* Update docs

* FW: HW sync (trigger mode) enabled for OAK-D-LR, for cameras with matching FPS

* Change default SIPP buffer sizes

* Add 3A skipping option to reduce CPU usage

* Change API to be able to configure isp 3A FPS

* Update BoarConfig with limits

* Update script node python bindings

* Update FW: Add workaround for BNO sequence number limit of 256 (sensors sends uint8)

* FW: camera sensor improvements:
- AR0234 improved AE smoothness, increased max gain to 400x (first 25.6x analog),
- OV9782 on RGB/CAM-A socket max FPS: 120 (previously was only for OV9282), also improves image quality in very bright light,
- OV9782/9282 minimum exposure time decreased: 20us -> 10us, helps in very bright light. TODO update tuning to make use of it, currently only possible to use with manual exposure

* Update stereo_depth_video.cpp

* Enable interrupt mode: Update BMI driver with fixes from: https://github.com/boschsensortec/BMI270-Sensor-API/pull/16

* Update ObjectTracker with improvements from rvc3

* Add API to set trackingPerClass in ObjectTracker node

* Update FW before merge

* Update FW with IMU fix for BNO

* Add IMU versioning; firmware versioning, firmware update status callbacks

* Update FW with fix for BMI timestamp

* Update FW: IMU support for OAK-D-SR

* Fix 'default constrictible' error on some compilers

* Update FW

* Add IMU FW update RPC

* Updated yolo description

* Update examples

* Update FW with deprecation warning for enableFirmwareUpdate

* Change imu version to imu type

* Update FW before merge

* Added C++14 requirement to examples & tests

* Tweaked crash_report example

* [FW] Added missing bindings for CameraControl and ImgFrame

* Update FW with fix for calibration load example

* fix stability_stress_test fail to link on ubuntu

- fixes luxonis/depthai-core#769

* fix isClosed/checkClosed threading, rpcClient exceptions

- remove thread-unsafe checkClosed()
- update isClosed() doxygen + comments
- protect DataInputQueue::maxDataSize with std::atomic
- remove unused dai::DeviceBase::rpcStream
- fixes luxonis/depthai-core#520

* fix var hides class member, this-> in constructors

- fix few compile warn 'ex' unreferenced local variable
- rename setBusId() param to not hide class member
- refactor XLinkConnection constructors
- partial fix luxonis/depthai-core#247

* fix: stdexcept header added for std::runtime_error

Signed-off-by: Onuralp SEZER <thunderbirdtr@fedoraproject.org>

* [FW] Removed UTF-8 degree sign from temperature prints. Closes: #773

* Move sipp buffer size from BoardConfig to GlobalProperties

* Update style

* Partially reverted bce144449056aa2a914bc70da526aebe2f359c32 - only kept the C++14 specified in examples, tests already had the version specified

* [Stereo] Add option to invalidate edge pixels on disparity/depth frame

* Update FW: handle disparity flipping

* Update FW: support for stereo.setOutputSize when LEFT or RIGHT alignment is set

* Update FW: support for stereo between RGB and LEFT/RIGHT

* [FW] ImageManip CSC improvements, New boards and power cycle fix

* FW: fix for UART0 / '/dev/ttyS0' init failure in Script node

* Update FW with fix for USB devices stuck after reboot

* Release v2.21.0

* updated version and changelot

* removed merge missing functions

---------

Signed-off-by: Onuralp SEZER <thunderbirdtr@fedoraproject.org>
Co-authored-by: alex-luxonis <alex@luxonis.com>
Co-authored-by: alex-luxonis <60824841+alex-luxonis@users.noreply.github.com>
Co-authored-by: TheMarpe <martin.peterlin7@gmail.com>
Co-authored-by: SzabolcsGergely <szabi@luxonis.com>
Co-authored-by: szabi-luxonis <60790666+szabi-luxonis@users.noreply.github.com>
Co-authored-by: moratom <47612463+moratom@users.noreply.github.com>
Co-authored-by: Matevz Morato <matevz.morato@gmail.com>
Co-authored-by: camblomquist <cameron@blomqu.ist>
Co-authored-by: Tommy <tomprochazka0@gmail.com>
Co-authored-by: Dale Phurrough <dale@hidale.com>
Co-authored-by: Erol444 <erol123444@gmail.com>
Co-authored-by: Cameron Blomquist <cblomquist@lsa2.com>
Co-authored-by: anonymous-1000 <124404305+anonymous-1000@users.noreply.github.com>
Co-authored-by: TheMarpe <martin@luxonis.com>
Co-authored-by: Onuralp SEZER <thunderbirdtr@fedoraproject.org>